services:
  - type: web
    name: stellarmarket
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: PORT
        value: 3000
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
